### ISSUE TITLE
Issue with segmentedradiogroup and xml editor

### ISSUE THREAD

**Issue by serandin** [vinc3m1/android-segmentedradiobutton#4]
I've been taking a look at the segmented control and it looks pretty cool. the one issue I'm having is that the control won't show in the UI editor. I get an error 'Could not resolve resource value: 0x7f02000f'. Everything seems to work when I run the app but it makes it impossible to layout the rest of the page in the editor.

I also noticed a typo in your xml. There was no + in the id for button_one.

Interesting. If I change the declaration in the xml from "<com.makerman...." to "<view class="com.makerman..." it works nicely in both the ui editor and when running the app. Problem solved I guess.

**Comment by vinc3m1** [comment]
the + only needs to be there on the first instance of an ID.

and adding the view class="... doesnt seem to work for me...
